id: P000765
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:01:51.039078
source_metadata:
  id: bdr:W20464
  title: ནོར་བཟང་གི་རྣམ་ཐར
  author: ''
  volumes:
    364302cf85184beaaabc8e297d526e93:
      image_group_id: I4752
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
