id: P000765
initial_creation_type: ocr
source_metadata:
  id: bdr:W20464
  title: ནོར་བཟང་གི་རྣམ་ཐར
  author: ''
  volumes:
    364302cf85184beaaabc8e297d526e93:
      image_group_id: I4752
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
